In [2]:
import numpy as np
import pandas as pd

In [12]:
def findX(lambda_fun, a, b, eps=0.000001):
    h = abs(b - a)/2
    left = [a]
    right = [b]
    y = [lambda_fun(b)]
    while h > eps:
        if lambda_fun(right[-1])* lambda_fun(right[-1] - h) > 0:
            right.append(right[-1] - h)
            y.append(lambda_fun(right[-1]))
            h = abs(right[-1] -left[-1])/2
        else:
            left.append(right[-1] - h)
            h = abs(right[-1] -left[-1])/2
    return right, y

In [16]:
x, y = findX(lambda x: x**3 +x**2 +x + 2,-2,0)
print(x)
print(y)
array = np.array([x, y]).transpose()
array.shape
df = pd.DataFrame(array, columns=['x', 'y'])
df

[0, -1.0, -1.25, -1.3125, -1.34375, -1.3515625, -1.3525390625, -1.35302734375, -1.3531494140625, -1.353179931640625, -1.3531951904296875, -1.3532028198242188, -1.3532066345214844, -1.3532085418701172]
[2, 1.0, 0.359375, 0.149169921875, 0.035552978515625, 0.006230831146240234, 0.0025394028052687645, 0.0006915020057931542, 0.00022929891383682843, 0.00011373389460800354, 5.594924794039002e-05, 2.7056390333957125e-05, 1.2609827961362896e-05, 5.38651338288787e-06]

           x         y
0   0.000000  2.000000
1  -1.000000  1.000000
2  -1.250000  0.359375
3  -1.312500  0.149170
4  -1.343750  0.035553
5  -1.351562  0.006231
6  -1.352539  0.002539
7  -1.353027  0.000692
8  -1.353149  0.000229
9  -1.353180  0.000114
10 -1.353195  0.000056
11 -1.353203  0.000027
12 -1.353207  0.000013
13 -1.353209  0.000005